### ISSUE TITLE
View Renderer Error Log Spam

### ISSUE THREAD

**Issue by WenXin20** [wolforcept/Vaultopic#1]
Minecraft v1.12.2
Forge v14.23.5.2838
Vaultopic v2.1

My log is constantly being spammed with the following error. I also haven't used any items from this mod yet, this happens as soon as the world loads.
```
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: java.lang.NoSuchMethodException: net.minecraft.client.renderer.EntityRenderer.setupCameraTransform(float, int)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at wolforce.vaultopic.client.Projector.<clinit>(Projector.java:27)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at wolforce.vaultopic.client.VIEWRenderer.onRenderWorldLastEvent(VIEWRenderer.java:91)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1252_VIEWRenderer_onRenderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:<clinit>:31]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: java.lang.NullPointerException
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at wolforce.vaultopic.client.Projector.loadMatrixes(Projector.java:49)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at wolforce.vaultopic.client.VIEWRenderer.onRenderWorldLastEvent(VIEWRenderer.java:91)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1252_VIEWRenderer_onRenderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1952)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1614)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1385)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[10:16:50] [Client thread/INFO]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[10:16:55] [Server thread/INFO]: Saving chunks for level 'Cinnamon 2 Pack v3 Backup'/overworld
```

**Comment by AterAnimAvis** [comment]
The reason for this is that the Projector class is looking for the MCP name of setupCameraTransform rather than the SRG name of func_78479_a.

The MCP name will work in dev but not production.
The SRG name will work in production but not dev.

Attached is a modified version of the Version 2.1 that should work in both environments (Rename to .jar).
[vaultopic-2.1_patched.zip](https://github.com/wolforcept/Vaultopic/files/3586767/vaultopic-2.1_patched.zip)

The only change was to the Projector class as follows.

From:
```java
    try {
      setupCameraTransform = net.minecraft.client.renderer.EntityRenderer.class.getDeclaredMethod("setupCameraTransform", float.class, int.class);
      setupCameraTransform.setAccessible(true);
    } catch (NoSuchMethodException|SecurityException e) {
      e.printStackTrace();
    }
```
To:
```java
    try {
      setupCameraTransform = net.minecraft.client.renderer.EntityRenderer.class.getDeclaredMethod("setupCameraTransform", float.class, int.class);
      setupCameraTransform.setAccessible(true);
    } catch (NoSuchMethodException|SecurityException ignored) {
      try {
        setupCameraTransform = net.minecraft.client.renderer.EntityRenderer.class.getDeclaredMethod("func_78479_a", float.class, int.class);
        setupCameraTransform.setAccessible(true);
      } catch (NoSuchMethodException|SecurityException e) {
        e.printStackTrace();
      }
    }
```

**Comment by asanetargoss** [comment]
If what @AterAnimAvis says is true, a more robust solution would be to use access transformers to allow accessing these kinds of things directly.

Or, when that's not possible or desirable, to use a system to automatically convert srgnames to the appropriate workspace names:
https://github.com/asanetargoss/Changeling/blob/3b5b2ace0cb6653d6235a861143db50a9969fbe4/src/main/java/mchorse/metamorph/entity/SoundHandler.java#L23
https://github.com/asanetargoss/Changeling/blob/c3be51bc98b32efe04f1a6af58572662fbfc355d/src/main/java/mchorse/metamorph/util/ObfuscatedName.java
https://github.com/asanetargoss/Changeling/blob/c3be51bc98b32efe04f1a6af58572662fbfc355d/src/main/java/mchorse/metamorph/util/DevMappings.java

**Comment by rlnt** [comment]
Could you please release that? It still spams like hell.

**Comment by katubug** [comment]
I am also here for this issue. Mine actually goes beyond just NPE errors - doing ctrl+f "vaultopic" in my latest.log brings up over 20,000 different instances.

**Comment by wolforcept** [comment]
Yeah sorry everyone about that. Havent been able to work on vaultopic (or any other mod) for a while, but will look at this before the end of the year.

**Comment by katubug** [comment]
No worries! Real life comes first. I'm glad to hear a fix may be forthcoming! Hope you have a lovely holiday, and that things aren't super crazy for you! 💗

**Comment by wolforcept** [comment]
Thank you! I applied the fix provided by @AterAnimAvis (THANK YOU) and it seems that the problem is fixed. Tested in a real normal minecraft installation.

**Comment by katubug** [comment]
Awesome, really glad to hear that! Thanks to both of you for all your hard work!

**Comment by katubug** [comment]
Just wanted to pop back and confirm that this issue is indeed fixed. I'm sure you know that, but I like to corroborate :P
